### ISSUE TITLE
Android Application faced fatal exception while creation of GraphRuntime object creation

### ISSUE THREAD

**Issue by PariksheetPinjari909** [dmlc/tvm#1023]
@tqchen 

While developing [Android standalone](https://github.com/dmlc/tvm/pull/980/commits/aa50fb2a383e8eb652821cc866767ddd18953bdf) application we face some native crash fatal exception problem while creating graph runtime java object 

src : tutorials/deployment/android/app/src/main/java/ml/dmlc/tvm/android/demo/MainActivity.java
line from +186 to +192

>            Function runtimeCreFun = Function.getFunction("tvm.graph_runtime.create");
>            TVMValue runtimeCreFunRes = runtimeCreFun.pushArg(modelGraph)
>                    .pushArg(modelLib)
>                    .pushArg(tvmCtx.deviceType)
>                    .pushArg(tvmCtx.deviceId)
>                    .invoke();
src : src/runtime/graph/graph_runtime.cc
line from +476 to +483

>  // Find the maximum space size.
>  int max_id = 0;
>  for (size_t i = 0; i < attrs_.shape.size();+i) {
>    max_id = std::max(attrs_.storage_id[i] 1, max_id);
>  }
>  for (uint32_t nid : input_nodes_) {
>    attrs_.storage_id[this->entry_id(nid, 0)] = max_id++;
>  }

after merge above snippet of code on graph_runtime.cc from old code tvm graph_runtime.cc, android standalone application able to run smoothly without any problem on target phone. Will you confirm is the right solution for what am facing tvm problem?

**Comment by tqchen** [comment]
Please update your local version of nnvm to the latest version, which should resolve this problem already

**Comment by PariksheetPinjari909** [comment]
with latest nnvm and tvm workspace with [Android Stand alone application](https://github.com/dmlc/tvm/pull/980/commits/aa50fb2a383e8eb652821cc866767ddd18953bdf) this bug still exists.

am wondering what is the dependency of nnvm on tvm android stand alone application(JVM + TVM Runtime) to resolve this problem?

**Comment by tqchen** [comment]
This is strange, because  https://github.com/dmlc/nnvm/blob/master/src/compiler/graph_fuse.cc#L195 is exactly this logic, except that we moved it to compile time.

Please double check if you have used the latest nnvm(and rebuild the nnvm dynamic lib)

**Comment by PariksheetPinjari909** [comment]
With latest Nnvm and Tvm workspace and compiled model (deploy_graph.json, deploy_lib.so and deploy_param.params) above problem is not able reproduce. 

Thanks
