### ISSUE TITLE
VTA simullation error: AttributeError: 'dict' object has no attribute 'TARGET'

### ISSUE THREAD

**Issue by diamantopoulos** [dmlc/tvm#3920]
Dear tvm team, 

I am trying to follow the steps to simulate TVM workloads on the VTA simulator from [docs.](https://docs.tvm.ai/vta/install.html#vta-fpga-toolchain-installation) 

The TARGET on vta/config/vta_config.json file is set to sim.

* 1st issue: `make vta` fails with unknown vta target.
* 2nd issue: 
`cd <tvm root>/vta/hardware/xilinx`
`make ip MODE=sim`
returns the following error:
![image](https://user-images.githubusercontent.com/15805984/64543389-6ac42180-d325-11e9-8f88-65948d6d713d.png)

I am using the latest version on master 6a377f7.

Is this a bug, or do I miss any step from docs?

Kindly thanks,
Dionysios

**Comment by cchung100m** [comment]
Hi @diamantopoulos 

for the first question, please ensure that you’ve properly installed the VTA python package:
`python <tvm root>/vta/tests/python/integration/test_benchmark_topi_conv2d.py`

can you dump the content of vta_config.json for double check?

You might can open a thread on [tvm forum](https://discuss.tvm.ai/) for further discussion by other tvm users.

**Comment by vegaluisjose** [comment]
Hey @diamantopoulos ,

This was fixed [here](https://github.com/dmlc/tvm/commit/83d2418a5844639477e3dc6ba6a499b7f43209a1), can you pull?

**Comment by diamantopoulos** [comment]
> Hi @diamantopoulos
> 
> for the first question, please ensure that you’ve properly installed the VTA python package:
> `python <tvm root>/vta/tests/python/integration/test_benchmark_topi_conv2d.py`
> 
> can you dump the content of vta_config.json for double check?

Hi @cchung100m , thanks for the hint. I've verified that VTA is properly installed (test_benchmark_topi_conv2d.py executes correctly). 
However I am still unable to execute `make vta`. Specifically, [the advanced configuration](https://docs.tvm.ai/vta/install.html#advanced-configuration-optional) does not work for me. I am getting the following error on a fresh tvm install (195973c0a136c739c15f238fb4db6b433bf505c6).

![image](https://user-images.githubusercontent.com/15805984/64853824-8fb5de80-d61c-11e9-9722-2993528979fd.png)

**Comment by diamantopoulos** [comment]
> Hey @diamantopoulos ,
> 
> This was fixed [here](https://github.com/dmlc/tvm/commit/83d2418a5844639477e3dc6ba6a499b7f43209a1), can you pull?

Hi @vegaluisjose , thanks a lot!

**Comment by tqchen** [comment]
Thanks for great discussions, for following up questions, you are more than welcomed to open a new thread on https://discuss.tvm.ai/
